public enum Menus
{
    TitleScreen,
    LoadingScreen,
    GeneralBattleMenu,
    MoveSelectionMenu,    
    PokemonInfoScreen,
    OpposingPokemonInfoScreen,
    AttackInfoScreen,
    AwaitingPlayerInputScreen,
    PokemonDamagedScreen,
    OpposingPokemonDamagedScreen,
    InBattlePartyMenu,
    PokemonFaintedScreen,
    DialogueScreen,
    ForfietMenu,
    WinScreen,
    LoseScreen,
    BlankScreen
}